server:
  port: 9000
spring:
  application:
    name: tsq-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: tsq-article #payment_routh #路由的ID，没有固定规则，但要求唯一，建议配合服务名
          #uri: http://localhost:8001  #匹配后提供服务的路由地址 没有进行负载均衡
          uri: lb://TSQ-ARTICLE #匹配后提供服务的路由地址
          predicates:
            - Path=/article/** #断言，路径相匹配的进行路由
        - id: tsq-rabbitMq #payment_routh #路由的ID，没有固定规则，但要求唯一，建议配合服务名
            #uri: http://localhost:8001  #匹配后提供服务的路由地址 没有进行负载均衡
          uri: lb://tsq-rabbitMq #匹配后提供服务的路由地址
          predicates:
            - Path=/notice/** #断言，路径相匹配的进行路由


eureka:
  instance:
    hostname: tsq-gateway
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://localhost:8686/eureka
